kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplyblock-pod-listing-role-binding
subjects:
- kind: ServiceAccount
  name: caching-node-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: simplyblock-pod-listing-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplyblock-pod-listing-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caching-node-service-account

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-node-handler
  labels:
    app: caching-node-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caching-node-handler
  template:
    metadata:
      labels:
        app: caching-node-handler
    spec:
      serviceAccountName: caching-node-service-account
      containers:
      - name: caching-node-handler
        image: simplyblock/caching-node-handler
        env:
        - name: SPDKCSI_SECRET
          valueFrom:
            secretKeyRef:
              name: spdkcsi-secret
              key: secret.json
        - name: CLUSTER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: spdkcsi-cm
              key: config.json
        - name: IFNAME
          value: "{{ .Values.cachingnode.ifname }}"
        - name: CPUMASK
          value: "{{ .Values.cachingnode.cpuMask }}"
        - name: SPDKMEM
          value: "{{ .Values.cachingnode.spdkMem }}"
        - name: SPDKIMAGE
          value: "{{ .Values.image.spdk.repository }}:{{ .Values.image.spdk.tag }}"
        - name: S3DATAPATH
          value: "{{ .Values.cachingnode.s3DataPath }}"
        - name: BLOCKEDPCIE
          value: "{{ .Values.cachingnode.blockedPcie }}"
        - name: FTLBUFFERSIZE
          value: "{{ .Values.cachingnode.ftlBufferSize }}"
        - name: LVSTORECLUSTERSIZE
          value: "{{ .Values.cachingnode.lvStoreClusterSize }}"
        - name: INITIALSTORESIZE
          value: "{{ .Values.cachingnode.initialStoreSize }}"
        - name: NUMPAGESPERCLUSTERRATIO
          value: "{{ .Values.cachingnode.numPagesPerClusterRatio }}"
        - name: S3BUCKETNAME
          value: "{{ .Values.cachingnode.s3BucketName }}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: Always
