# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
appVersion: latest
description: Simplyblock CSI Driver for Kubernetes
name: spdk-csi
version: "v0.3.0"
keywords:
- spdk
- csi
- spdk-csi
home: https://github.com/simplyblock-io/spdk-csi
sources:
- https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
