# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: Secret
metadata:
  name: spdkcsi-secret
stringData:
  # Specify node specific token with item "name" matches ConfigMap.
  # {
  #   "name": "spdk-testnode",
  #   "username": "myuser",
  #   "password": "mypass"
  # }
  secret.json: |-
    {
      "simplybk": {
        "secret": "RhOaHtnL7cr0kPXk7WD7"
      }
    }
---
apiVersion: v1
Kind: Secret
metadata: 
  name: simplyblock-pvc-keys
  namespace: default
data:
  crypto_key1: N2IzNjk1MjY4ZTJhNjYxMWEyNWFjNGIxZWUxNWYyN2Y5YmY2ZWE5NzgzZGFkYTY2YTRhNzMwZWJmMDQ5MmJmZA==
  crypto_key2: Nzg1MDU2MzZjODEzM2Q5YmU0MmUzNDdmODI3ODViODFhODc5Y2Q4MTMzMDQ2ZjhmYzBiMzZmMTdiMDc4YWQwYw==
